[build]
  # Set base directory to current directory (client folder)
  base = "."
  
  # Build command
  command = "pnpm build"
  
  # Directory to publish (where build output goes)
  publish = "dist"

[dev]
  # Development command  
  command = "pnpm dev"
  
  # Port for local development
  port = 3000